### ISSUE TITLE
[ERROR] Hmm got any ideas?

### ISSUE THREAD

**Issue by Bioblaze** [josephbmanley/build-godot-action#23]
`
Godot Engine v4.0.3.stable.official.5222a99f5 - https://godotengine.org/
libX11.so.6: cannot open shared object file: No such file or directory
ERROR: Can't load Xlib dynamically.
   at: DisplayServerX11 (platform/linuxbsd/x11/display_server_x11.cpp:5254)
ERROR: Unable to create DisplayServer, all display drivers failed.
   at: setup2 (main/main.cpp:20[18](https://github.com/Bioblaze/godot2d_mmo_client/actions/runs/5036433447/jobs/9032577335#step:5:19))
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: BUG: Unreferenced static string to 0: interface_added
Your video card drivers seem not to support the required Vulkan version.
   at: unref (core/string/string_name.cpp:1[31](https://github.com/Bioblaze/godot2d_mmo_client/actions/runs/5036433447/jobs/9032577335#step:5:32))

If possible, consider updating your video card drivers or using the OpenGL 3 driver.

You can enable the OpenGL 3 driver by starting the engine from the
command line with the command:

    "godot" --rendering-driver opengl3

If you recently updated your video card drivers, try rebooting.
`

**Comment by Calinou** [comment]
You need to run Godot 4 with the `--headless` command line argument.

**Comment by Bioblaze** [comment]
yeah in the codebase on this github action it isn't being done. I forked and modified :p and got it working.

**Comment by Calinou** [comment]
This will be fixed by https://github.com/yeslayla/build-godot-action/pull/22 once it's merged.
