### ISSUE TITLE
Enable build on debug mode

### ISSUE THREAD

**Issue by raphaklaus** [josephbmanley/build-godot-action#6]
Hello! Great job on this action! It would be nice optionally support `--export-debug` option.

https://github.com/josephbmanley/build-godot-action/blob/master/entrypoint.sh#L22

**Comment by yeslayla** [comment]
Hi @raphaklaus, thanks for using the action! :smile:

I included this in release [v1.3.3](https://github.com/josephbmanley/build-godot-action/releases/tag/v1.3.3). Let me know if you have any issues!
