### ISSUE TITLE
Consider using a permissive license like MIT

### ISSUE THREAD

**Issue by Calinou** [josephbmanley/build-godot-action#9]
This repository is currently [licensed under the GPLv3](https://github.com/josephbmanley/build-godot-action/blob/3ba8e158e182e3c596d73d36d33237fe353e7e70/LICENSE). This may be problematic for people working in companies as their legal department may forbid using any kind of GPL-licensed software.

Using a permissive license like MIT would avoid possible legal confusion. Not to mention a copyleft license is often difficult to enforce in a small project like this one :slightly_smiling_face:

**Comment by yeslayla** [comment]
Hmmm... I see what you are saying. I generally by default use GPL in my projects to discourage closed source changes, but I can see where that may appear problematic in the commercial space. I'll go ahead and update to an MIT license.

**Comment by yeslayla** [comment]
License has been updated.
